---
site_title: "My server site"
bg_color_start: "#4facfe"
bg_color_end: "#00f2fe"
text_color: "#ffffff"
welcome_message: "Welcom on my server"
description: "This page generateg for Ansible template"
year: "2026"
author: "Tvarb1na"

